flags:
  client:
    paths:
      - packages/client/src
    carryforward: true
  sdk:
    paths:
      - packages/sdk/src
    carryforward: true
coverage:
  status:
    project:
      default:
        flags:
          - client
          - sdk
      client:
        target: 80%
        flags:
          - client
      sdk:
        target: 80%
        flags:
          - sdk
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null
