
export enum Shurikens {
	"Razor" = "Razor"
,	"Playing Cards" = "Playing Cards"
,	"Chalk" = "Chalk"
,	"Dart" = "Dart"
,	"Vintage Cards" = "Vintage Cards"
,	"Onyx Dagger" = "Onyx Dagger"
,	"Throwing Stars" = "Throwing Stars"
,	"Charm" = "Charm"
,	"Willow Leaf Spike" = "Willow Leaf Spike"
,	"Chakram" = "Chakram"
,	"Apricot Flower Tag" = "Apricot Flower Tag"
,	"Venom Dart" = "Venom Dart"
,	"Dharma Chakram" = "Dharma Chakram"
,	"Plumbata" = "Plumbata"
,	"Cards of Tyranny" = "Cards of Tyranny"
,	"Mystic Jade Charm" = "Mystic Jade Charm"
,	"Fuhma Shuriken" = "Fuhma Shuriken"
,	"Wind and Fire Wheels" = "Wind and Fire Wheels"
,	"Azure Dagger" = "Azure Dagger"
,	"Flechette" = "Flechette"
,	"Frost Venom Dart" = "Frost Venom Dart"
,	"Death Rune" = "Death Rune"
,	"Sudarsana" = "Sudarsana"
,	"Petal Torrent" = "Petal Torrent"

}
