import { Heads } from './Heads';
import { Chests } from './Chests';
import { Arms } from './Arms';
import { Legs } from './Legs';
import { Accessories } from './Accessories';

export * from './Heads';
export * from './Chests';
export * from './Arms';
export * from './Legs';
export * from './Accessories';

export const Armors = {
	Heads,
	Chests,
	Arms,
	Legs,
	Accessories
};

export enum ArmorsEnum {
	'Hairband' = 'Hairband',
	'Hat' = 'Hat',
	'Laced Quiver' = 'Laced Quiver',
	'Bike Helmet' = 'Bike Helmet',
	'Mask' = 'Mask',
	'Circlet' = 'Circlet',
	'Beret' = 'Beret',
	'Chain Coif' = 'Chain Coif',
	'Safety Helmet' = 'Safety Helmet',
	'Ballistic Helmet' = 'Ballistic Helmet',
	'Fire Helmet' = 'Fire Helmet',
	'Tiara' = 'Tiara',
	'Crown' = 'Crown',
	'Close Helm' = 'Close Helm',
	'Motorcycle Helmet' = 'Motorcycle Helmet',
	'Crystal Tiara' = 'Crystal Tiara',
	'Mithril Helm' = 'Mithril Helm',
	'Tactical OPS Helmet' = 'Tactical OPS Helmet',
	'Helm of Banneret' = 'Helm of Banneret',
	'Chinese Opera Mask' = 'Chinese Opera Mask',
	'Imperial Crown' = 'Imperial Crown',
	'Imperial Burgonet' = 'Imperial Burgonet',
	'Laurel Wreath' = 'Laurel Wreath',
	'Windbreaker' = 'Windbreaker',
	"Monk's Robe" = "Monk's Robe",
	'Wetsuit' = 'Wetsuit',
	'Fabric Armor' = 'Fabric Armor',
	'Leather Armor' = 'Leather Armor',
	'Leather Jacket' = 'Leather Jacket',
	'Turtle Dobok' = 'Turtle Dobok',
	'Military Suit' = 'Military Suit',
	'Bikini' = 'Bikini',
	'Patched Robe' = 'Patched Robe',
	'Dress' = 'Dress',
	'Diving Suit' = 'Diving Suit',
	'Rider Jacket' = 'Rider Jacket',
	'Sunset Armor' = 'Sunset Armor',
	'Covert Agent Uniform' = 'Covert Agent Uniform',
	'Chain Armor' = 'Chain Armor',
	'Suit' = 'Suit',
	'Qipao' = 'Qipao',
	'Sheet Metal Armor' = 'Sheet Metal Armor',
	'Hanbok' = 'Hanbok',
	'Bulletproof Vest' = 'Bulletproof Vest',
	'Optical Camouflage Suit' = 'Optical Camouflage Suit',
	'EOD Suit' = 'EOD Suit',
	"Butler's Suit" = "Butler's Suit",
	"Rocker's Jacket" = "Rocker's Jacket",
	'Mithril Armor' = 'Mithril Armor',
	'Crusader Armor' = 'Crusader Armor',
	'Amazoness Armor' = 'Amazoness Armor',
	'Dragon Dobok' = 'Dragon Dobok',
	"Commander's Armor" = "Commander's Armor",
	'Battle Suit' = 'Battle Suit',
	'Kabana' = 'Kabana',
	'Queen of Hearts' = 'Queen of Hearts',
	'Blazing Dress' = 'Blazing Dress',
	'Watch' = 'Watch',
	'Bandage' = 'Bandage',
	'Bracelet' = 'Bracelet',
	'Squad Leader Armband' = 'Squad Leader Armband',
	'Leather Shield' = 'Leather Shield',
	'Bracer' = 'Bracer',
	'Sheath' = 'Sheath',
	'Cube Watch' = 'Cube Watch',
	'Golden Bracelet' = 'Golden Bracelet',
	'Bazuband' = 'Bazuband',
	'Crimson Bracelet' = 'Crimson Bracelet',
	'Steel Shield' = 'Steel Shield',
	'Sword Stopper' = 'Sword Stopper',
	'Mithril Shield' = 'Mithril Shield',
	'Vital Sign Sensor' = 'Vital Sign Sensor',
	'Draupnir' = 'Draupnir',
	'Creed of the Knight' = 'Creed of the Knight',
	'Sword of Shah Jahan' = 'Sword of Shah Jahan',
	'Bracelet of Skadi' = 'Bracelet of Skadi',
	'Auto-arms' = 'Auto-arms',
	'Radar' = 'Radar',
	'Slippers' = 'Slippers',
	'Running Shoes' = 'Running Shoes',
	'Tights' = 'Tights',
	'Knee Pads' = 'Knee Pads',
	'Chain Leggings' = 'Chain Leggings',
	'High Heels' = 'High Heels',
	'Heelys' = 'Heelys',
	'Repaired Slippers' = 'Repaired Slippers',
	'Boots' = 'Boots',
	'Steel Knee Pads' = 'Steel Knee Pads',
	'Straitjacket Sneakers' = 'Straitjacket Sneakers',
	'Maverick Runner' = 'Maverick Runner',
	'Combat Boots' = 'Combat Boots',
	'Killer Heels' = 'Killer Heels',
	'Feather Boots' = 'Feather Boots',
	'Mithril Boots' = 'Mithril Boots',
	'Bucephalus' = 'Bucephalus',
	'White Rhinos' = 'White Rhinos',
	'EOD Boots' = 'EOD Boots',
	'Red Shoes' = 'Red Shoes',
	'Glacial Shoes' = 'Glacial Shoes',
	'Boots of Hermes' = 'Boots of Hermes',
	'Feather' = 'Feather',
	'Flower' = 'Flower',
	'Ribbon' = 'Ribbon',
	'Fan' = 'Fan',
	'Buddhist Scripture' = 'Buddhist Scripture',
	'Box' = 'Box',
	'Holy Grail' = 'Holy Grail',
	'Cross' = 'Cross',
	'Binoculars' = 'Binoculars',
	'Gilded Quill Fan' = 'Gilded Quill Fan',
	"Saint's Relic" = "Saint's Relic",
	'Flower of Fate' = 'Flower of Fate',
	'Glass Pieces' = 'Glass Pieces',
	'Doll' = 'Doll',
	'Sniping Scope' = 'Sniping Scope',
	'Buddha Sarira' = 'Buddha Sarira',
	'Quiver' = 'Quiver',
	'Feather Duster' = 'Feather Duster',
	'Powder of Life' = 'Powder of Life',
	'Uchiwa' = 'Uchiwa',
	'Magazine' = 'Magazine',
	'Moonlight Pendant' = 'Moonlight Pendant',
	"Schrodinger's Box" = "Schrodinger's Box",
	'Veritas Lux Mea' = 'Veritas Lux Mea',
	'White Crane Fan' = 'White Crane Fan',
	'Glacial Ice' = 'Glacial Ice',
	'True Samadhi Fire' = 'True Samadhi Fire',
	'Emerald Tablet' = 'Emerald Tablet'
}

export type Armors = typeof Armors;
