
export enum Legs {
	"Slippers" = "Slippers"
,	"Running Shoes" = "Running Shoes"
,	"Tights" = "Tights"
,	"Knee Pads" = "Knee Pads"
,	"Chain Leggings" = "Chain Leggings"
,	"High Heels" = "High Heels"
,	"Heelys" = "Heelys"
,	"Repaired Slippers" = "Repaired Slippers"
,	"Boots" = "Boots"
,	"Steel Knee Pads" = "Steel Knee Pads"
,	"Straitjacket Sneakers" = "Straitjacket Sneakers"
,	"Maverick Runner" = "Maverick Runner"
,	"Combat Boots" = "Combat Boots"
,	"Killer Heels" = "Killer Heels"
,	"Feather Boots" = "Feather Boots"
,	"Mithril Boots" = "Mithril Boots"
,	"Bucephalus" = "Bucephalus"
,	"White Rhinos" = "White Rhinos"
,	"EOD Boots" = "EOD Boots"
,	"Red Shoes" = "Red Shoes"
,	"Glacial Shoes" = "Glacial Shoes"
,	"Boots of Hermes" = "Boots of Hermes"

}
