
export enum Drinks {
	"Honey" = "Honey"
,	"Water" = "Water"
,	"Ice" = "Ice"
,	"Whiskey" = "Whiskey"
,	"Coffee" = "Coffee"
,	"Carbonated Water" = "Carbonated Water"
,	"Milk" = "Milk"
,	"Boiling Water" = "Boiling Water"
,	"Lemonade" = "Lemonade"
,	"Water Bottle" = "Water Bottle"
,	"Baijiu" = "Baijiu"
,	"Soju" = "Soju"
,	"Ice Coffee" = "Ice Coffee"
,	"Cocktail" = "Cocktail"
,	"Coffee Liqueur" = "Coffee Liqueur"
,	"Cola" = "Cola"
,	"Latte" = "Latte"
,	"Honey Milk" = "Honey Milk"
,	"Highball" = "Highball"
,	"Chocolate Milk" = "Chocolate Milk"
,	"Honey Water" = "Honey Water"
,	"Ice Water" = "Ice Water"
,	"On The Rocks" = "On The Rocks"
,	"Cowboy" = "Cowboy"
,	"Kaoliang Liquor" = "Kaoliang Liquor"
,	"Hot Honey Water" = "Hot Honey Water"
,	"Flower Liquor" = "Flower Liquor"
,	"Americano" = "Americano"
,	"Herbal Liquor" = "Herbal Liquor"
,	"Whiskey Cocktail" = "Whiskey Cocktail"
,	"Purified Water" = "Purified Water"
,	"Can of Cola" = "Can of Cola"
,	"Hot Chocolate" = "Hot Chocolate"
,	"White Russian" = "White Russian"

}
