
export enum Specials {
	"Surveillance Camera" = "Surveillance Camera"
,	"Snare" = "Snare"
,	"Mouse Trap" = "Mouse Trap"
,	"Piano Wire" = "Piano Wire"
,	"Spiked Plank" = "Spiked Plank"
,	"Enhanced Mouse Trap" = "Enhanced Mouse Trap"
,	"Dynamite" = "Dynamite"
,	"Bamboo Trap" = "Bamboo Trap"
,	"Booby Trap" = "Booby Trap"
,	"Clang Clatter" = "Clang Clatter"
,	"Telephoto Camera" = "Telephoto Camera"
,	"Jungle Guillotine" = "Jungle Guillotine"
,	"Explosive Trap" = "Explosive Trap"
,	"Pendulum Axe" = "Pendulum Axe"
,	"Mine" = "Mine"
,	"RDX" = "RDX"
,	"Mithril String" = "Mithril String"
,	"Hidden Maiden" = "Hidden Maiden"
,	"Fire Trap" = "Fire Trap"
,	"C-4" = "C-4"
,	"Double Guillotine" = "Double Guillotine"
,	"Claymore" = "Claymore"
,	"Stingburst" = "Stingburst"
,	"Remote Mine" = "Remote Mine"
,	"Smart Bomb" = "Smart Bomb"

}
