export enum Gloves {
	'Brass Knuckles' = 'Brass Knuckles',
	'Cotton Glove' = 'Cotton Glove',
	'Leather Glove' = 'Leather Glove',
	'Iron Knuckles' = 'Iron Knuckles',
	'Gauntlet' = 'Gauntlet',
	'Wing Knuckles' = 'Wing Knuckles',
	'Bone Gauntlet' = 'Bone Gauntlet',
	'Shatter Shell Gauntlet' = 'Shatter Shell Gauntlet',
	'Glass Knuckles' = 'Glass Knuckles',
	'Phoenix Gloves' = 'Phoenix Gloves',
	'One Inch Punch' = 'One Inch Punch',
	'Divine Fist' = 'Divine Fist',
	'Bloodwing Knuckles' = 'Bloodwing Knuckles',
	'Frost Petal Hand' = 'Frost Petal Hand',
	"Buddha's Palm" = "Buddha's Palm",
	'Brasil Gauntlet' = 'Brasil Gauntlet',
	'White Claw Punch' = 'White Claw Punch',
	'Imperial Silk Glove' = 'Imperial Silk Glove'
}
