export const WEIGHTS = {
	ITEM_COUNT: 6,
	EQUIPMENT: {
		WEAPON: 100,
		ARMOR: 5,
		HEAD: 1,
		ARM: 1,
		ACCESSORY: 1,
		LEG: 1
	},
	MAXIMUM_LOCATIONS: 6,
	MINIMUM_ITEM_THRESHOLD: 1,
	SHORT_ITEM_THRESHOLD: 1,
	LOCATION_MODIFIER: 100,
	TELEPORT_MODIFIER: 1.05,
	ITEM_PERCENTAGE_MODIFIER: 10
};
