export const WEIGHTS = {
  ITEM_COUNT: 6,
  EQUIPMENT: {
    WEAPON: 100,
    ARMOR: 5,
    HEAD: 1,
    ARM: 1,
    ACCESSORY: 1,
    LEG: 1
  },
  MAXIMUM_LOCATIONS: 5,
  NEEDED_ITEM_THRESHOLD: 4,
  MINIMUM_ITEM_THRESHOLD: 1,
  SHORT_ITEM_THRESHOLD: 3,
  LOCATION_MODIFIER: 100,
  TELEPORT_MODIFIER: 0.9,
  ITEM_PERCENTAGE_MODIFIER: 10
};
